<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8" />
        <title>PowerShell live documentation</title>
        <link rel="stylesheet" type="text/css" href="style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.0/styles/default.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
        <script charset="UTF-8" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/languages/powershell.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <div id="content">
            <header>
                <h1>PowerShell live documentation</h1>
                <p id="versions-tested-line">Versions tested: <span class="tested-version">5.1.1007</span>, <span class="tested-version">6.0.0</span>, <span class="tested-version">6.0.1</span>, <span class="tested-version">6.0.2</span>, <span class="tested-version">6.0.3</span>, <span class="tested-version">6.0.4</span>, <span class="tested-version">6.0.5</span>, <span class="tested-version">6.1.0</span>, <span class="tested-version">6.1.1</span>, <span class="tested-version">6.1.2</span>, <span class="tested-version">6.1.3</span>, <span class="tested-version">6.1.4</span>, <span class="tested-version">6.1.5</span>, <span class="tested-version">6.1.6</span>, <span class="tested-version">6.2.0</span>, <span class="tested-version">6.2.1</span>, <span class="tested-version">6.2.2</span>, <span class="tested-version">6.2.3</span>, <span class="tested-version">6.2.4</span>, <span class="tested-version">6.2.5</span>, <span class="tested-version">7.0.0</span>, <span class="tested-version">7.0.1</span></p>
            </header>
            <main> <section><h2>Variable $? in parentheses</h2>
<p>In PowerShell, the <code>$?</code> variable represents the exit status of the
previous command. If it's true, the command succeeded. If it's false, the
command failed. However, you need to be careful if using the variable, since
enclosing a command in parentheses can reset <code>$?</code> to true in
PowerShell 5 and earlier.</p>
<pre class="code-view"><code class="powershell">$local:ErrorActionPreference = "SilentlyContinue"

Write-Error error
Write-Output "outside of parentheses: `$? = $?"

(Write-Error error)
Write-Output "inside of parentheses: `$? = $?"
</code></pre><table class="output-table"><caption>Output by version</caption><thead><tr><th>5.x, 6.x</th> <th>7.x</th></tr></thead><tbody><tr><td><pre class="output-text">outside of parentheses: $? = False
inside of parentheses: $? = True</pre></td><td><pre class="output-text">outside of parentheses: $? = False
inside of parentheses: $? = False</pre></td></tr></tbody></table></section> <section><h2>The WriteError function</h2>
<p>When <code>$ErrorActionPreference</code> is <code>Stop</code>,
<code>$PSCmdlet.WriteError</code> exits the current advanced function and
throws. However, the exception it throws is not catchable from within the
advanced function.</p>
<pre class="code-view"><code class="powershell">function TestWriteErrorFunction {
    [CmdletBinding()]
    param()

    $local:ErrorActionPreference = "Stop"
    try {
        $PSCmdlet.WriteError((NewErrorRecord "error in try"))
    } catch {
        Write-Output "caught inside the cmdlet: $_"
    }

    Write-Output "after the try-catch"
}

try {
    TestWriteErrorFunction
} catch {
    Write-Output "caught outside the cmdlet: $_"
}
</code></pre><table class="output-table"><caption>Output by version</caption><thead><tr><th>5.x, 6.x, 7.x</th></tr></thead><tbody><tr><td><pre class="output-text">caught outside the cmdlet: error in try</pre></td></tr></tbody></table>
<p><code>Write-Error</code>, on the other hand, is catchable inside the function,
for both advanced and basic functions.</p>
<pre class="code-view"><code class="powershell">function TestWriteErrorCmdletAdvanced {
    [CmdletBinding()]
    param()

    $local:ErrorActionPreference = "Stop"
    try {
        Write-Error "error in try"
    } catch {
        Write-Output "caught inside the cmdlet: $_"
    }

    Write-Output "after the try-catch"
}

function TestWriteErrorCmdletBasic {
    param()

    $local:ErrorActionPreference = "Stop"
    try {
        Write-Error "error in try"
    } catch {
        Write-Output "caught inside the cmdlet: $_"
    }

    Write-Output "after the try-catch"
}

Write-Output "testing advanced function"
try {
    TestWriteErrorCmdletAdvanced
} catch {
    Write-Output "caught outside the cmdlet: $_"
}

Write-Output ""

Write-Output "testing basic function"
try {
    TestWriteErrorCmdletBasic
} catch {
    Write-Output "caught outside the cmdlet: $_"
}
</code></pre><table class="output-table"><caption>Output by version</caption><thead><tr><th>5.x, 6.x, 7.x</th></tr></thead><tbody><tr><td><pre class="output-text">testing advanced function
caught inside the cmdlet: error in try
after the try-catch

testing basic function
caught inside the cmdlet: error in try
after the try-catch</pre></td></tr></tbody></table></section>             </main>
        </div>
    </body>
</html>
